### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by nagalun**

### CODE REVIEW

**Comment by dhbaird** [comment]
This patch looks fairly good, and also backwards compatibility is preserved. Will review more and do some testing and get back.

**Comment by nagalun** [comment]
Is there any problem with the patch?

**Comment by turpault** [comment]
ping ? It's been 4 years already :-)

**Comment by nagalun** [comment]
Well, this patch worked perfectly for me back when I was using this library, but I don't use it anymore, so I have no real interest in rebasing/fixing these changes... You're free to take the patch and update it, though.

**Pull request closed without merging**
